/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;


import Ultilities.HibernateUltis;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;

/**
 *
 * @author Dell
 */
public class TestHDCT extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form TestHDCT
     */
    public TestHDCT() {
        initComponents();
        setColumn();
//        loadTable(listHDCT());
    }
    
    void setColumn(){
        String [] a  ={"Mã hóa đơn","Mã sản phẩm","Đơn giá","Số lượng","Tổng tiền"};
        model.setColumnIdentifiers(a);
        tblHDCT.setModel(model);
        
    }
    
//    void loadTable(List<HDCT> list){
//        while(model.getRowCount()>0){
//            model.removeRow(0);
//        }
//        for (HDCT x : list) {
//            model.addRow(new Object[]{x.getMaHoaDon().getMaHoaDon(),x.getMaSanPham().getMaSanPham(),x.getDonGia(),x.getSoLuong(),x.getTongTien()});
//        }
//        model.fireTableDataChanged();
//    }
//    
//    public List<HDCT> listHDCT(){
//        List<HDCT> list;
//        try ( Session ss = HibernateUltis.getSessionFactory().openSession()) {
//            String sql = "select  y from HDCT y";
//            TypedQuery<HDCT> type = ss.createQuery(sql,HDCT.class);
//            list = type.getResultList();
//        }
//        return list;
//    }
//    
//    public float tongTien(List<HDCT> list){
//        float a = 0;
//        for (HDCT x : list) {
//            a+=x.getTongTien();
//        }
//        return a;
//    }
//    
//    
void bieudo(){
    float a;
    
       DefaultCategoryDataset data = new DefaultCategoryDataset();
       
        data.setValue(19900,"","P01");
        data.setValue(188,"","P02");
           data.setValue(1888,"","P02");
        data.setValue(20000,"","P03");
         
        JFreeChart jfree = ChartFactory.createBarChart("", "", "", data, PlotOrientation.HORIZONTAL, false, false, false);
        CategoryPlot catpl = jfree.getCategoryPlot();
        catpl.setRangeGridlinePaint(Color.black);
        ChartPanel chatpannel = new ChartPanel(jfree);
         jpn1.removeAll();
        jpn1.add(chatpannel,BorderLayout.CENTER);
        jpn1.validate();
    
}
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHDCT = new javax.swing.JTable();
        txtTongDoanhThu = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jpn1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHDCT);

        txtTongDoanhThu.setText("jLabel1");

        jButton1.setText("Xem tổng doanh thu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jpn1.setBackground(new java.awt.Color(51, 51, 255));
        jpn1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1)
                .addComponent(txtTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(78, 78, 78)
                .addComponent(jpn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        txtTongDoanhThu.setText("Tổng doanh thu của bạn là :  " + String.valueOf(tongTien(listHDCT())) +" VNĐ");
//        bieudo(listHDCT());
bieudo();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestHDCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestHDCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpn1;
    private javax.swing.JTable tblHDCT;
    private javax.swing.JLabel txtTongDoanhThu;
    // End of variables declaration//GEN-END:variables
}
